import './globals.css'

import Footer from '@/components/footer/footer'


export const metadata = {
  title: 'آموزشگاه دانشگاه البرز',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa"
          dir='ltr'>
      <body>
        {children}
        <Footer/>
      </body>
      
    </html>
  )
}
